### PR TITLE
Fix SVG/XML, refer to issue #1

### PR DESCRIPTION
**Pull request by versable**
When opening the file in Inkscape, it complains with:
raptor.svg:1: parser warning : Unsupported version '1.1'

```
<?xml version="1.1" encoding="UTF-8"?>
                   ^
WARNING: unknown type: svg:description
perl-raptor/raptor.svg:1: parser warning : 
Unsupported version '1.1'
<?xml version="1.1" encoding="UTF-8"?>
```

Just save the file as optimized for web in Inkscape to resolve the issue

### CODE REVIEW

**Comment by versable** [comment]
Also note that Github displays the new version correctly:
  https://github.com/versable/perl-raptor/blob/e2786ba860699e9a736340e8f0cf051ef1fdde91/raptor.svg

Opposed to the old file:
  https://github.com/kraih/perl-raptor/blob/master/raptor.svg

**Comment by kraih** [comment]
I don't want all that extra metadata.

**Comment by versable** [comment]
Removed metadata in commit 656c7345baeed38abb41099c862bf56d7da6e8a3

**Comment by kraih** [comment]
The XML version has been fixed. https://github.com/kraih/perl-raptor/commit/9e04614f4fb39ae14608dd62d714405fa70f2ae9

**Comment by versable** [comment]
Viewbox is still skewed:
https://github.com/kraih/perl-raptor/blob/9e04614f4fb39ae14608dd62d714405fa70f2ae9/raptor.svg

**Pull request closed without merging**
